feat(actix-web) api proxy
greenpress/gateway pull request #14
Opened 2021-01-21 00:31 UTC by benukhanov

See commits from Jan 20, 2021.

2021-01-30 05:10 UTC, LironHazan commented on src/main.rs
> +// TODO: Add some #[cfg(test)]
we can remove the comment and add an issue for unit tests

2021-01-30 05:18 UTC, LironHazan commented on src/main.rs
> +        // NOTE: Consequently, the *first* middleware registered
really?? sounds strange

2021-01-30 05:30 UTC, LironHazan commented on src/proxy/api_proxy.rs
> +    let mut user: String = "".to_owned();
nice 👍

2021-01-30 05:42 UTC, LironHazan commented on src/proxy/api_proxy.rs
> +        // const meUrl = getProxyTarget(authService) + '/api/me'
can we extract the if block content to a function that returns a populated user string? call it: **init_user**(..) for e.g.
It could reduce the noises of reading a lot of code :)

2021-01-30 05:45 UTC, LironHazan commented on src/proxy/api_proxy.rs
> +        let me_url_protocol = &app_config.auth_service.protocol;
lines 31 - 36 can also move to a function that returns me_url, would cleanup as well

2021-01-30 05:46 UTC, LironHazan commented on src/proxy/api_proxy.rs
> +        .header(USER_HEADER, user.to_owned()) // proxyReq.setHeader('user', req.user || '')
remove comment

2021-01-30 05:47 UTC, LironHazan commented on src/proxy/api_proxy.rs
> +        // if (setCookie)
remove comment

2021-01-30 05:47 UTC, LironHazan commented on src/proxy/api_proxy.rs
> +            // res.set('set-cookie', setCookie)
remove comment

2021-01-30 05:47 UTC, LironHazan commented on src/proxy/api_proxy.rs
> +        // const setCookie = response.headers.raw()['set-cookie']
remove comment

2021-01-30 05:47 UTC, LironHazan commented on src/proxy/api_proxy.rs
> +    let bearer_token = get_bearer_token(&req); // req.headers.authorization
remove comment

2021-01-30 05:47 UTC, LironHazan commented on src/proxy/api_proxy.rs
> +    let cookie_token = req.cookie("token"); // req.headers.cookie.includes('token=')
remove comment

2021-01-30 05:48 UTC, LironHazan commented on src/proxy/api_proxy.rs
> +        // req.user = user
remove comment

2021-01-30 05:53 UTC, LironHazan commented on src/utils/proxy.rs
> +    for service in services {
could be extracted to a function that returns thee list of the mutated services, **set_proxy_addr()**

2021-01-30 05:53 UTC, LironHazan commented on src/utils/proxy.rs
> +        // if app_config.content_service
either the comment is not clear or should be removed

2021-01-30 05:55 UTC, LironHazan requested changes
@benukhanov Great job, I learned from you PR 🚀 
I left some comments :)

2021-01-30 15:46 UTC, benukhanov commented on src/main.rs
> +// TODO: Add some #[cfg(test)]
cool, we already have an issue for unit tests

2021-01-30 15:52 UTC, benukhanov commented on src/main.rs
> +        // NOTE: Consequently, the *first* middleware registered
that's what they said:

![image](https://user-images.githubusercontent.com/13782467/106360897-b8c73400-6323-11eb-95d5-2001f8284da5.png)

2021-01-30 16:07 UTC, benukhanov commented on src/proxy/api_proxy.rs
> +        // const meUrl = getProxyTarget(authService) + '/api/me'
Yes, I tried to do it and spent a lot of time on it. The reason is in this code:

![image](https://user-images.githubusercontent.com/13782467/106361257-9cc49200-6325-11eb-9da1-674d235f8d02.png)

Then we must use "return" and the forward function must stop. It was a bit tricky to do this with another function (and also we have parameters, like "req").

I suggest making sure everything is tested and working here, and later we can find a better way to break this down into another function (in a different PR).

2021-01-30 16:57 UTC, benukhanov commented on src/proxy/api_proxy.rs
> +        let me_url_protocol = &app_config.auth_service.protocol;
done :)

2021-01-30 17:23 UTC, benukhanov commented on src/utils/proxy.rs
> +    for service in services {
to extract "let services = vec!..." and "for service in services... for..." into another function? 

we also need to do set_proxy_port() then, right? 

set_proxy_addr() will return anything?

2021-01-30 18:39 UTC, LironHazan commented on src/proxy/api_proxy.rs
> +        // const meUrl = getProxyTarget(authService) + '/api/me'
ok no problem :)

2021-01-30 18:45 UTC, LironHazan commented on src/utils/proxy.rs
> +    for service in services {
it's actually seems reduced now, did you tweak that?

2021-01-30 18:50 UTC, benukhanov commented on src/utils/proxy.rs
> +    for service in services {
I removed comments :)

2021-01-30 18:52 UTC, benukhanov commented on src/proxy/api_proxy.rs
> +        // const meUrl = getProxyTarget(authService) + '/api/me'
cool. by the way, after I removed the comments, it became a bit shorter

2021-01-30 18:58 UTC, benukhanov commented on src/utils/proxy.rs
> +    for service in services {
so let me know what do you think

2021-02-05 05:40 UTC, LironHazan commented
@benukhanov let's test and merge?

2021-02-15 10:45 UTC, benukhanov commented
@LironHazan I think it's better to do this:

./src/tests/api_proxy.rs (unit tests only)
./tests/.../ (integration tests, like testing the API)

Instead of:

./src/api_proxy/tests.rs

and then the conflict resolved. In this PR the folder renamed from api_proxy to proxy.

---

https://doc.rust-lang.org/book/ch11-03-test-organization.html

2021-02-15 10:51 UTC, benukhanov commented
> @benukhanov let's test and merge?

@LironHazan I've tested locally using Postman and mostly the code works. Later, we'll need to do full testing of all greenpress services (frontend, backend, etc.).

Let's merge this PR so Robert can do unit and integration tests as well.

2021-03-26 06:45 UTC, LironHazan approved these changes
@benukhanov thanks !!!

2021-03-26 07:24 UTC, merged